# Generated by Django 6.0.4 on 2026-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'активный'), ('complete', 'завершенный'), ('canceled', 'отмененный')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
