# Generated by Django 6.0.4 on 2026-06-08 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Промокод')),
                ('discount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Конец действия')),
                ('active', models.BooleanField(default=True)),
                ('apply_now', models.IntegerField(default=0, verbose_name='Сколько применено')),
                ('apply_max', models.IntegerField(verbose_name='Максимально применений')),
            ],
        ),
    ]
